print("Syötä Henkilötiedot")
print("-----------------------")
etunimet = input("Anna etunimet")
sukunimi = input("Anna sukunimi")
puhelinnumero = input("Anna puhelinnumero")
sähköpostiosoite = input("Anna sähköpostiosoite")
lähiosoite = input("Anna lähiosoite")
postinumero = input("Anna postinumero")
kaupunki = input("Anna kaupunki")
maa = input("Anna maa")
syntymävuosi = input("Anna syntymävuosi")
print("Kiitos")

print()
print("HENKILÖN TIEDOT")
print("------------------")
print("NIMI:")
print(f"\t{sukunimi},{etunimet}")
print("PUH:")
print(f"{puhelinnumero}")
print("E-MAIL:")
print(f"{sähköpostiosoite}")
print("OSOITE:")
print(f"{lähiosoite}, {postinumero}, {kaupunki}, {maa}")
