print("*************************")
print("*    Valuuttamuunnin    *")
print("*************************")
kurssi = float(input("Anna dollarin kurssi euroina:"))
raha = float(input("Anna rahan määrä euroina:"))
print(f"Rahan arvo on dollareina: {raha/kurssi:.2f}")
print("*******************************")